load-balance between scaled-up coordinator units
canonical/tempo-coordinator-k8s-operator pull request #59
Opened 2024-10-11 10:42 UTC by michaeldmitry

## Issue
When the coordinator is scaled up, this doesn't reflect in the ingress configuration of `traefik_route`. So, requests to traefik will always be proxied to one unit of the coordinator although we might have multiple units in place.

## Solution
Listen on `peer_relation_created` hook to populate peer data with hostnames of each coordinator unit and when constructing the ingress configuration, we retrieve the servers urls from the peer data.

 ## Drive-bys
 - Remove any DNS reference in the worker config to the coordinator or traefik DNS names and depend solely on the workers' DNS names. The rationale behind that is that the worker config sent to a worker should indicate that this config is sufficient and we can run a worker process with no need for sth outside the worker to be ready. i.e: If we pass traefik's hostname as `tls_server_name` in the worker config, at any point in time, traefik can now be under TLS and our worker will suddenly fail as it needs Traefik's CA..
 - Update `CertHandler` lib
 
 ## Testing Considerations
 TODO

2024-10-14 07:10 UTC, PietroPasotti requested changes
some concerns about how we're implementing the peers relation data protocol, would like to use a more generic pattern, the rest looks good.

2024-10-14 07:10 UTC, PietroPasotti commented on src/charm.py
> +    def generate_lb_server_config(self, scheme: str, port: int) -> List[Dict[str, str]]:
```suggestion
    def _build_lb_server_config(self, scheme: str, port: int) -> List[Dict[str, str]]:
```

for consistency with the other `_build_*_config` methods

2024-10-14 07:10 UTC, PietroPasotti commented on src/charm.py
> +        self.framework.observe(self.on[PEER].relation_created, self._on_peer_data_created)
```suggestion
        self.framework.observe(self.on[PEER].relation_created, self._on_peers_relation_created)
```

2024-10-14 07:10 UTC, PietroPasotti commented on src/charm.py
> +PEER = "peers"
```suggestion
PEERS_RELATION_ENDPOINT_NAME = "peers"
```

2024-10-14 07:10 UTC, PietroPasotti commented on src/charm.py
> +HOSTNAME_KEY = "hostname"
this should be included in a pydantic model, not hardcoded in a global

2024-10-14 07:10 UTC, PietroPasotti commented on src/charm.py
> +    def set_peer_unit_data(self, key: str, data: Any) -> None:
Side-note: given also loki/mimir will probably need something similar, making this information available in the coordinator (next to `Coordinator.peer_addresses`) doesn't seem like a bad idea.

Speaking of, why are we not using `Coordinator.peer_addresses` instead? do we need fqdns for TLS?

2024-10-14 07:55 UTC, michaeldmitry commented on src/charm.py
> +    def set_peer_unit_data(self, key: str, data: Any) -> None:
I'm not sure I 100% follow.
There should not be any other code modifying peer data. If you mean the other coordinator units, each unit is setting to its own databag, so I'm not sure I understand where would the interfering come from.

2024-10-14 07:58 UTC, michaeldmitry commented on src/charm.py
> +    def set_peer_unit_data(self, key: str, data: Any) -> None:
I thought about putting that in the shared object, but this usecase is only valid for Tempo (mimir and loki's IngressPerApp/Unit would automatically do what we want to do with peer data). I thought that one string key is not that error-prone to add a whole databag model for it (inspired by https://github.com/canonical/grafana-k8s-operator/blob/main/src/charm.py#L561 :D). WDYT?

2024-10-14 07:58 UTC, michaeldmitry commented on lib/charms/observability_libs/v1/cert_handler.py
> +                "DEPRECATION WARNING. `refresh_events` is now deprecated. CertHandler will automatically refresh the CSR when necessary."
This and the above comment should be updated in `observability-libs`

2024-10-14 07:59 UTC, michaeldmitry commented on src/charm.py
> +    def set_peer_unit_data(self, key: str, data: Any) -> None:
"Speaking of, why are we not using Coordinator.peer_addresses instead? do we need fqdns for TLS?"
Yes. I need fqdns for TLS and grpc URLs

2024-10-16 11:38 UTC, PietroPasotti approved these changes
couple more nits, doesn't need another pass from me

2024-10-16 11:38 UTC, PietroPasotti commented on src/charm.py
> +    """Peer data between the coordinator units."""
```suggestion
    """Databag model for the "peers" relation between coordinator units."""
```

2024-10-16 11:38 UTC, PietroPasotti commented on src/charm.py
> +    """FQDN hostname of a coordinator unit."""
```suggestion
    """FQDN hostname of this coordinator unit."""
```

2024-10-16 11:38 UTC, PietroPasotti commented on src/charm.py
> +    hostname: str
I think we should rename this to "fqdn", so it's more obvious what it means and more future-proof. What if the next time we need to add another type of hostname? what do we call it?

2024-10-16 14:00 UTC, merged