added resolver directive
canonical/tempo-coordinator-k8s-operator pull request #66
Opened 2024-11-11 14:35 UTC by PietroPasotti

Fixes https://github.com/canonical/cos-lib/issues/94

This change tells Nginx to update the IP whenever it changes.
To test:
deploy COS-lite plus Tempo HA.
refresh tempo worker with any locally packed charm
verify you can ping the /ready endpoint on port 3200 soon (max 5sec) after the new worker service has reported ready.

2024-11-11 18:42 UTC, mmkay requested changes
One important overlook (running it with TLS), rest are rather cosmetic remarks.

2024-11-11 18:42 UTC, mmkay commented on src/nginx_config.py
> +                *self._resolver(custom_resolver=_get_dns_ip_address()),
It's not added when TLS is on - you also need to add it in line 249. Probably the same problem exists in all other tandem PRs.

2024-11-12 09:07 UTC, PietroPasotti commented on src/nginx_config.py
> +    resolv = Path("/etc/resolv.conf").read_text()
fair point, we can store it somewhere in a global or in the charm.

2024-11-12 10:53 UTC, mmkay approved these changes

2024-11-15 14:32 UTC, merged