Add a way to configure extra receivers for uncharmed applications
canonical/tempo-coordinator-k8s-operator pull request #7
Opened 2024-06-26 10:55 UTC by michaeldmitry

## Issue
Fixes #87

## Solution
Expose juju config options to force enable each protocol supported by Tempo.

## Testing instructions
TODO

2024-06-28 12:44 UTC, PietroPasotti requested changes
looking good!
not sure why this PR and the other both share a bunch of apparently overlapping changes to the test code (such as the commented-out modules). 
+100 for fixing the tests, but still I'd have preferred to have a single pr to fix the tests, then two PRs on top of that doing the receivers and the pydantic port.

This makes it quite hard to review the test code changes.
For the next time :) 
Now let's try to merge these two.

2024-06-28 12:44 UTC, PietroPasotti commented on src/charm.py
> +                for receiver in get_args(ReceiverProtocol)
TIL

2024-06-28 12:44 UTC, PietroPasotti commented on src/tempo.py
> -        self.enabled_receivers = enable_receivers or []
the comment in line 269 still includes an outdated reference to this attribute

2024-06-28 12:44 UTC, PietroPasotti commented on tests/scenario/test_enabled_receivers.py
> +        assert charm.enabled_receivers == set(["otlp_http"])
```suggestion
        assert charm.enabled_receivers == {"otlp_http"}
```

2024-06-28 12:44 UTC, PietroPasotti commented on tests/scenario/test_enabled_receivers.py
> +        assert charm.enabled_receivers == set(["otlp_http", "zipkin"])
```suggestion
        assert charm.enabled_receivers == {"otlp_http", "zipkin"}
```

2024-06-28 12:44 UTC, PietroPasotti commented on charmcraft.yaml
> +      description: force enable a receiver for Tempo's 'zipkin' protocol.
also apply to all others:

```suggestion
      description: Force-enable the receiver for the 'zipkin' protocol in Tempo, even if there is no integration currently requesting it.
```

2024-06-28 12:47 UTC, mmkay commented on charmcraft.yaml
> +    always_enable_zipkin:
They aren't receiver protocols per se - kafka and opencensus are disabled in the charm altogether while tempo_http and tempo_grpc are server ports so no traces will be coming in through them.

2024-06-30 22:05 UTC, michaeldmitry commented
> looking good! not sure why this PR and the other both share a bunch of apparently overlapping changes to the test code (such as the commented-out modules). +100 for fixing the tests, but still I'd have preferred to have a single pr to fix the tests, then two PRs on top of that doing the receivers and the pydantic port.
> 
> This makes it quite hard to review the test code changes. For the next time :) Now let's try to merge these two.

100% agreed. Will take care next time.
Comments on the overlapping changes for test files will be addressed in https://github.com/canonical/tempo-coordinator-k8s-operator/pull/5

2024-07-01 11:30 UTC, PietroPasotti approved these changes

2024-07-01 11:30 UTC, PietroPasotti commented on charmcraft.yaml
> +    always_enable_zipkin:
in that case we have some confusion in the types and enums around the code that we NEED to fix. See the ReceiverProtocol enum

2024-07-01 11:30 UTC, PietroPasotti commented on charmcraft.yaml
> +    always_enable_zipkin:
let's open a new issue for it

2024-07-01 11:38 UTC, merged